# Generated by Django 2.2.1 on 2019-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlusOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choise', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
