# Generated by Django 2.2.1 on 2019-06-17 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plusone',
            name='data',
        ),
        migrations.AddField(
            model_name='plusone',
            name='feedback',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
